AllCops:
  # Include gemspec and Rakefile
  Include:
    - "**/*.gemspec"
    - "**/Rakefile"
    - "**/config.ru"
    - "db/migrate/**/*"
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "spec/i18n_spec.rb"
    - "spec/dummy/**/*"
    - "spec/internal/**/*"
    - "vendor/**/*"

  # By default, the rails cops are not run. Override in project or home
  # directory .rubocop.yml files, or by giving the -R/--rails option.
  RunRailsCops: true
  # Cop names are not displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the -D/--display-cop-names
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding DisplayStyleGuide, or by giving the
  # -S/--display-style-guide option.
  DisplayStyleGuide: true
  # Additional cops that do not reference a style guide rule may be enabled by
  # default. Change behavior by overriding StyleGuideCopsOnly, or by giving
  # the --only-guide-cops option.
  StyleGuideCopsOnly: false

Metrics/AbcSize:
  Exclude:
    - "db/migrate/**/*"

# FIXME: Enable, correct the code, and remove this setting
Metrics/LineLength:
  # Max: 120
  Enabled: true
  Exclude:
    - "db/**/*"
    - "script/rails"

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - "db/migrate/**/*"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: true
  Exclude:
    - "db/migrate/**/*"
    - "spec/**/*"

# FIXME: Enable and correct the code
Style/MultilineOperationIndentation:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - "**/*.gemspec"

Style/SingleSpaceBeforeFirstArg:
  Enabled: true
  Exclude:
    - "db/**/*"

Style/SpaceAroundOperators:
  MultiSpaceAllowedForOperators:
    - "="
    - "=>"
    - "||="

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - "script/rails"
